var chalk = require('chalk')
var logger = require('./visual/logger')

function examples() {
  logger('')
  logger('   Examples:')
  logger('')
  logger('  The flags in brackets eg: [-o chalk] are to be run in the terminal like so: pkgparse -o chalk')
  logger('')
  logger(chalk.yellow('   I\'ve assumed your file is not always called package.json so you have to specify it.'))
  logger('')
  logger('   [-f] by itself will scan the current directory (use pwd) your terminal window is at')
  logger('')
  logger('   [-f ~/Development/0050_pkgparse/package.json]')
  logger('')
  logger('   [-f /usr/local/oddplacefora/package.json]')
  logger('')
  logger('   [-s tape] would return info about the module tape')
  logger('')
  logger('   [-d inu] would return the dependencies that inu relies on')
  logger('')
  logger('   [-o pkgparse] would open the pkgparse npm page in your default browser')
  logger('')
  logger('   [-o promise chrome] would open the promise npm page in chrome')
  logger('')
  logger('   [-o superagent firefox] would open the superagent npm page in firefox')
  logger('')
  logger(chalk.yellow('   Technically speaking, you can run any application with -o but you\'ll void your warranty!'))
  logger('')
}

module.exports = examples
